# Basic Information 
title: Yanan Wu
position: Lecturer
affiliation: China Agricultural University
affiliation_link: https://www.cau.edu.cn/
affiliation_logo: ./assets/img/bjtu02.png
email: ynwu (at) cau.edu.cn

# Search Engine Optimization (SEO)
keywords: yanan wu, wu yanan, yananwu, wuyanan
canonical: https://ynanwu.github.io
description: Yanan Wu is a CS Ph.D. student at China Agricultural University. Her research lies in meta-learning, incremental learning, and transfer learning.

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: true

# The option is used to show the last update time.
enable_last_update: false

# Links
google_scholar: https://scholar.google.com.hk/citations?user=h1SE2-0AAAAJ&hl=zh-CN
cv_link: https://drive.google.com/file/d/1ma7jwB0kUUHAEXxqLgy6vvhyjCn2_bWm/view?usp=share_link
github_link: https://github.com/ynanwu
linkedin: https://www.linkedin.com/in/yanan-wu-703160298/
twitter: https://twitter.com/yananwu0510

# Images 
avatar: ./assets/img/avatar01.jpeg
favicon: ./assets/img/favicon-wu.png
favicon_dark: ./assets/img/favicon-wu.png

# Footnotes
footnote: Feel free to use my website's source code.
footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
clustrmaps_id: l3lesztPwCz-uXlzFI1Lt9SB3Ctz-pBQuMdYqnD0Ul8

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
